default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: smaia
  password: smaia
  host: localhost

development:
  <<: *default
  database: Chov_development

test:
  <<: *default
  database: Chov_test

production:
  <<: *default
  database: Chov_production
  username: Chov
  password: <%= ENV['CHOV_DATABASE_PASSWORD'] %>
